### ISSUE TITLE
Assertion Failure at omr/compiler/x/codegen/OMRRegisterDependency.hpp:208: newCursor <= _numPostConditions

### ISSUE THREAD

**Issue by luke-li-2003** [eclipse-omr/omr#7467]
The assertion at `omr/compiler/x/codegen/OMRRegisterDependency.hpp:208` fails when building with message "Too many dependencies" on  x86_64_linux for Java 11

**Comment by 0xdaryl** [comment]
What test were you running that exposed this problem?  Can you post the backtrace from the assert here?

**Comment by 0xdaryl** [comment]
@BradleyWood : please investigate when more info is available.  @hzongaro FYI.

**Comment by hzongaro** [comment]
Note that [that line of code in `compiler/x/codegen/OMRRegisterDependency.hpp`](https://github.com/eclipse-omr/omr/blob/d226de41c45b803990717bceb88afd0705a16ef6/compiler/x/codegen/OMRRegisterDependency.hpp#L208) is a `TR_ASSERT`, so this must have involved an OpenJ9 `PROD_ASSUMES` build.

**Comment by luke-li-2003** [comment]
It *was* failing when run with `PROD_WITH_ASSUMES` during the build. I believe it have already been addressed with https://github.com/eclipse-openj9/openj9/pull/20211. I might have forgotten to link this to the PR.
